name: "WinBuildAndTest"

on:
  push:

jobs:
  build-and-test:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
        toolchain: [mingw]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Install MinGW
        run: choco install mingw

      - name: Add MinGW to PATH
        run: echo "C:\tools\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: xmake f -p ${{ matrix.toolchain }} --mode=${{ matrix.config }} --root -c -vy
      - run: xmake build -vy
      - run: xmake test -vy '*/default'
